module.exports = {
    allAdventurers: [
        "Undercover Grace, Flame, Sword",
        "Chrom, Flame, Sword",
        "Hunter Berserker, Flame, Sword",
        "Lea, Flame, Sword",
        "Marth, Flame, Sword",
        "Naveed, Flame, Sword",
        "Serena, Flame, Sword",
        "Karl, Flame, Sword",
        "The Prince, Flame, Sword",
        "Valentine's Orion, Flame, Sword",
        "Marty, Flame, Sword",
        "Armored Yachiyo, Flame, Blade",
        "Nobunaga, Flame, Blade",
        "Rena, Flame, Blade",
        "Mikoto, Flame, Blade",
        "Laxi, Flame, Blade",
        "Aoi, Flame, Blade",
        "Summer Mitsuhide, Flame, Dagger",
        "Gala Laxi, Flame, Dagger",
        "Ezelith, Flame, Dagger",
        "Yuya, Flame, Dagger",
        "Melsa, Flame, Dagger",
        "Renelle, Flame, Dagger",
        "Gala Gatov, Flame, Axe",
        "Child Ranzal, Flame, Axe",
        "Halloween Mym, Flame, Axe",
        "Ramona, Flame, Axe",
        "Yue, Flame, Axe",
        "Vanessa, Flame, Axe",
        "Panther, Flame, Lance",
        "Kimono Elisanne, Flame, Lance",
        "Nadine, Flame, Lance",
        "Gala Mym, Flame, Lance",
        "Emma, Flame, Lance",
        "Xuan Zang, Flame, Lance",
        "Alain, Flame, Lance",
        "Summer Alex, Flame, Bow",
        "Chelsea, Flame, Bow",
        "Gala Sarisse, Flame, Bow",
        "Valentine's Ezelith, Flame, Bow",
        "Joe, Flame, Bow",
        "Yukata Cleo, Flame, Wand",
        "Seimei, Flame, Wand",
        "Incognito Nefaria, Flame, Wand",
        "Mega Man, Flame, Wand",
        "Student Maribelle, Flame, Wand",
        "Sinoa, Flame, Wand",
        "Xania, Flame, Wand",
        "Ayaha & Otoha, Flame, Staff",
        "Kuzunoha, Flame, Staff",
        "Yukata Cassandra, Flame, Staff",
        "Valentine's Hildegarde, Flame, Staff",
        "Halloween Lowen, Flame, Staff",
        "Verica, Flame, Staff",
        "Aurien, Flame, Staff",
        "Dragonyule Ilia, Flame, Manacaster",
        "Faris, Flame, Manacaster",
        "Gala Leonidas, Flame, Manacaster",
        "Summer Ieyasu, Water, Sword",
        "Eugene, Water, Sword",
        "Summer Celliera, Water, Sword",
        "Xander, Water, Sword",
        "Halloween Odetta, Water, Sword",
        "Zardin, Water, Sword",
        "Regina, Water, Blade",
        "Gala Mascula, Water, Blade",
        "Halloween Akasha, Water, Blade",
        "Valerio, Water, Blade",
        "Summer Ranzal, Water, Blade",
        "Celliera, Water, Blade",
        "Jurota, Water, Blade",
        "Humanoid Mercury, Water, Dagger",
        "Tiki, Water, Dagger",
        "Mitsuba, Water, Dagger",
        "Dragonyule Cleo, Water, Dagger",
        "Renee, Water, Dagger",
        "Orsem, Water, Dagger",
        "Luther, Water, Dagger",
        "Finni, Water, Axe",
        "Lazry, Water, Axe",
        "Gala Elisanne, Water, Axe",
        "Summer Julietta, Water, Axe",
        "Karina, Water, Axe",
        "Pietro, Water, Axe",
        "Rex, Water, Axe",
        "Faeblessed Tobias, Water, Lance",
        "Catherine, Water, Lance",
        "Fjorm, Water, Lance",
        "Xainfried, Water, Lance",
        "Gauld, Water, Lance",
        "Elisanne, Water, Lance",
        "Jakob, Water, Lance",
        "Cibella, Water, Lance",
        "Pinon, Water, Bow",
        "Hunter Sarisse, Water, Bow",
        "Laranoa, Water, Bow",
        "Dragonyule Nefaria, Water, Bow",
        "Waike, Water, Bow",
        "Forager Cleo, Water, Wand",
        "Yurius, Water, Wand",
        "Lily, Water, Wand",
        "Pipple, Water, Wand",
        "Summer Estelle, Water, Wand",
        "Dragonyule Xander, Water, Wand",
        "Sandalphon, Water, Staff",
        "Dragonyule Lily, Water, Staff",
        "Jiang Ziya, Water, Staff",
        "Nurse Aeleen, Water, Staff",
        "Thaniel, Water, Staff",
        "Ricardt, Water, Staff",
        "Sharpshooter Sarisse, Water, Manacaster",
        "Yoshitsune, Water, Manacaster",
        "Lapis, Water, Manacaster",
        "Nino, Wind, Sword",
        "Mona, Wind, Sword",
        "Gala Leif, Wind, Sword",
        "Wedding Elisanne, Wind, Sword",
        "Gala Ranzal, Wind, Sword",
        "Templar Hope, Wind, Sword",
        "Ku Hai, Wind, Sword",
        "Harle, Wind, Blade",
        "Yukata Lathna, Wind, Blade",
        "Forager Mitsuba, Wind, Blade",
        "Tobias, Wind, Blade",
        "Victor, Wind, Blade",
        "Addis, Wind, Blade",
        "Musashi, Wind, Blade",
        "Melody, Wind, Blade",
        "Dragonyule Nevin, Wind, Dagger",
        "Gala Notte, Wind, Dagger",
        "Summer Norwin, Wind, Dagger",
        "Wedding Aoi, Wind, Dagger",
        "Su Fang, Wind, Dagger",
        "Francesca, Wind, Dagger",
        "Shingen, Wind, Axe",
        "Kimono Luca, Wind, Axe",
        "Summer Amane, Wind, Axe",
        "Valentine's Melody, Wind, Axe",
        "Lin You, Wind, Axe",
        "Ranzal, Wind, Axe",
        "Johanna, Wind, Axe",
        "Izumo, Wind, Lance",
        "Grimnir, Wind, Lance",
        "Halloween Melsa, Wind, Lance",
        "Kirsty, Wind, Lance",
        "Sylas, Wind, Lance",
        "Pia, Wind, Lance",
        "Aeleen, Wind, Lance",
        "Humanoid Midgardsormr, Wind, Bow",
        "Valentine's Chelsea, Wind, Bow",
        "Meene, Wind, Bow",
        "Hawk, Wind, Bow",
        "Louise, Wind, Bow",
        "Joachim, Wind, Bow",
        "Eleonora, Wind, Bow",
        "Philia, Wind, Bow",
        "Basileus, Wind, Wand",
        "Myriam, Wind, Wand",
        "Summer Sinoa, Wind, Wand",
        "Maribelle, Wind, Wand",
        "Dragonyule Xainfried, Wind, Wand",
        "Noelle, Wind, Wand",
        "Nicolas, Wind, Wand",
        "Formal Noelle, Wind, Staff",
        "Akasha, Wind, Staff",
        "Wedding Xania, Wind, Staff",
        "Lowen, Wind, Staff",
        "Sophie, Wind, Staff",
        "Cecile, Wind, Manacaster",
        "Saiga, Wind, Manacaster",
        "Formal Joachim, Wind, Manacaster",
        "Civilian Leif, Light, Sword",
        "Pecorine, Light, Sword",
        "Gala Prince, Light, Sword",
        "Alfonse, Light, Sword",
        "Albert, Light, Sword",
        "Odetta, Light, Sword",
        "Raemond, Light, Sword",
        "Humanoid Jupiter, Light, Blade",
        "Mordecai, Light, Blade",
        "Gala Luca, Light, Blade",
        "Beautician Zardin, Light, Blade",
        "Hanabusa, Light, Blade",
        "Yachiyo, Light, Blade",
        "Halloween Edward, Light, Blade",
        "Farren, Light, Dagger",
        "Yukata Curran, Light, Dagger",
        "Wu Kong, Light, Dagger",
        "Mitsuhide, Light, Dagger",
        "Fleur, Light, Dagger",
        "Fritz, Light, Dagger",
        "Irfan, Light, Dagger",
        "Gala Audric, Light, Axe",
        "Sophie (Persona), Light, Axe",
        "Zhu Bajie, Light, Axe",
        "Dragonyule Malora, Light, Axe",
        "Julietta, Light, Axe",
        "Summer Luca, Light, Axe",
        "Linus, Light, Axe",
        "Ryszarda, Light, Lance",
        "Sharena, Light, Lance",
        "Hunter Vanessa, Light, Lance",
        "Halloween Elisanne, Light, Lance",
        "Annelie, Light, Lance",
        "Sha Wujing, Light, Lance",
        "Ryozen, Light, Lance",
        "Malka, Light, Lance",
        "Isaac, Light, Bow",
        "Summer Mikoto, Light, Bow",
        "Summer Cleo, Light, Bow",
        "Elias, Light, Bow",
        "Rawn, Light, Bow",
        "Luca, Light, Bow",
        "Malora, Light, Bow",
        "Summer Chelle, Light, Wand",
        "Radiant Xuan Zang, Light, Wand",
        "Peony, Light, Wand",
        "Lucretia, Light, Wand",
        "Chitose, Light, Wand",
        "Amane, Light, Wand",
        "Xiao Lei, Light, Wand",
        "Gala Zena, Light, Staff",
        "Hildegarde, Light, Staff",
        "Felicia, Light, Staff",
        "Vixel, Light, Staff",
        "Halloween Althemia, Light, Staff",
        "Estelle, Light, Staff",
        "Hope, Light, Staff",
        "Halloween Laxi, Light, Manacaster",
        "Eirene, Light, Manacaster",
        "Ilia, Light, Manacaster",
        "Sharpshooter Joe, Light, Manacaster",
        "Alberius, Shadow, Sword",
        "Gala Alex, Shadow, Sword",
        "Yaten, Shadow, Sword",
        "Audric, Shadow, Sword",
        "Berserker, Shadow, Sword",
        "Rodrigo, Shadow, Sword",
        "Gala Zethia, Shadow, Blade",
        "Linnea, Shadow, Blade",
        "Natalie, Shadow, Blade",
        "Ieyasu, Shadow, Blade",
        "Aldred, Shadow, Blade",
        "Durant, Shadow, Blade",
        "Taro, Shadow, Blade",
        "Summer Prince, Shadow, Dagger",
        "Joker, Shadow, Dagger",
        "Nevin, Shadow, Dagger",
        "Bellina, Shadow, Dagger",
        "Delphi, Shadow, Dagger",
        "Alex, Shadow, Dagger",
        "Orion, Shadow, Dagger",
        "Vida, Shadow, Dagger",
        "Vice, Shadow, Dagger",
        "Dragonyule Victor, Shadow, Axe",
        "Summer Patia, Shadow, Axe",
        "Curran, Shadow, Axe",
        "Sazanka, Shadow, Axe",
        "Erik, Shadow, Axe",
        "Yukimura, Shadow, Lance",
        "Summer Leonidas, Shadow, Lance",
        "Lathna, Shadow, Lance",
        "Forte, Shadow, Lance",
        "Patia, Shadow, Lance",
        "Botan, Shadow, Lance",
        "Zace, Shadow, Lance",
        "Halloween Sylas, Shadow, Bow",
        "Opera Karina, Shadow, Bow",
        "Chelle, Shadow, Bow",
        "Valentine's Addis, Shadow, Bow",
        "Nefaria, Shadow, Bow",
        "Norwin, Shadow, Bow",
        "Vania, Shadow, Wand",
        "Zena, Shadow, Wand",
        "Cassandra, Shadow, Wand",
        "Gala Cleo, Shadow, Wand",
        "Veronica, Shadow, Wand",
        "Kleimann, Shadow, Wand",
        "Althemia, Shadow, Wand",
        "Grace, Shadow, Staff",
        "Summer Verica, Shadow, Staff",
        "Heinwald, Shadow, Staff",
        "Cleo, Shadow, Staff",
        "Edward, Shadow, Staff",
        "Summer Mym, Shadow, Manacaster",
        "Gala Chelle, Shadow, Manacaster",
    ],
    uniqueDragon: [
        "Halloween Mym, Flame, Axe",
        "Gala Mym, Flame, Lance",
        "Mega Man, Flame, Wand",
        "Ayaha & Otoha, Flame, Staff",
        "Gala Leonidas, Flame, Manacaster",
        "Humanoid Mercury, Water, Dagger",
        "Humanoid Midgardsormr, Wind, Bow",
        "Humanoid Jupiter, Light, Blade",
        "Summer Chelle, Light, Wand",
        "Lathna, Shadow, Lance",
        "Chelle, Shadow, Bow",
        "Gala Chelle, Shadow, Manacaster",
    ],
    dragonDrive: [
        "Tiki, Water, Dagger",
        "Farren, Light, Dagger",
        "Nino, Wind, Sword",
        "Bellina, Shadow, Dagger",
        "Aldred, Shadow, Blade",
        "Yurius, Water, Wand",
        "Summer Mym, Shadow, Manacaster",
        "Summer Leonidas, Shadow, Lance",
        "Izumo, Wind, Lance",
        "Gala Notte, Wind, Dagger",
        "Sandalphon, Water, Staff",
        "Panther, Flame, Lance",
        "Mona, Wind, Sword",
        "Sophie (Persona), Light, Axe",
        "Joker, Shadow, Dagger",
        "Gala Zethia, Shadow, Blade",
    ],
};