module.exports = {
  allAdventurers: [
    {
      id: '110059_02',
      name: 'Undercover Grace',
      element: 'Flame',
      weapon: 'Sword',
      aliases: 'ugrace',
    },
    {
      id: '110359_01',
      name: 'Chrom',
      element: 'Flame',
      weapon: 'Sword',
      limited: true,
    },
    {
      id: '110050_02',
      name: 'Hunter Berserker',
      element: 'Flame',
      weapon: 'Sword',
      limited: true,
      aliases: 'hberserker, hzerker',
    },
    {
      id: '110259_01',
      name: 'Lea',
      element: 'Flame',
      weapon: 'Sword',
    },
    {
      id: '110291_01',
      name: 'Marth',
      element: 'Flame',
      weapon: 'Sword',
      limited: true,
    },
    {
      id: '110266_01',
      name: 'Naveed',
      element: 'Flame',
      weapon: 'Sword',
    },
    {
      id: '110054_01',
      name: 'Serena',
      element: 'Flame',
      weapon: 'Sword',
      rarity: 4,
    },
    {
      id: '110008_01',
      name: 'Karl',
      element: 'Flame',
      weapon: 'Sword',
      rarity: 4,
    },
    {
      id: '100001_01',
      name: 'The Prince',
      element: 'Flame',
      weapon: 'Sword',
      rarity: 4,
      aliases: 'euden, oof',
    },
    {
      id: '110052_03',
      name: 'Valentine\'s Orion',
      element: 'Flame',
      weapon: 'Sword',
      rarity: 3,
      aliases: 'vorion',
    },
    {
      id: '110261_01',
      name: 'Marty',
      element: 'Flame',
      weapon: 'Sword',
      rarity: 3,
    },
    {
      id: '110064_02',
      name: 'Armored Yachiyo',
      element: 'Flame',
      weapon: 'Blade',
      aliases: 'ayachiyo',
    },
    {
      id: '110346_01',
      name: 'Nobunaga',
      element: 'Flame',
      weapon: 'Blade',
      limited: true,
    },
    {
      id: '110264_01',
      name: 'Rena',
      element: 'Flame',
      weapon: 'Blade',
    },
    {
      id: '110010_01',
      name: 'Mikoto',
      element: 'Flame',
      weapon: 'Blade',
    },
    {
      id: '100032_01',
      name: 'Laxi',
      element: 'Flame',
      weapon: 'Blade',
      rarity: 4,
    },
    {
      id: '110002_01',
      name: 'Aoi',
      element: 'Flame',
      weapon: 'Blade',
      rarity: 3,
    },
    {
      id: '110345_03',
      name: 'Summer Mitsuhide',
      element: 'Flame',
      weapon: 'Dagger',
      limited: true,
      aliases: 'smitsuhide',
    },
    {
      id: '100032_04',
      name: 'Gala Laxi',
      element: 'Flame',
      weapon: 'Dagger',
      limited: true,
      aliases: 'glaxi, galaxi',
    },
    {
      id: '110011_01',
      name: 'Ezelith',
      element: 'Flame',
      weapon: 'Dagger',
    },
    {
      id: '110344_01',
      name: 'Yuya',
      element: 'Flame',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110270_01',
      name: 'Melsa',
      element: 'Flame',
      weapon: 'Dagger',
      rarity: 4,
      limited: true,
    },
    {
      id: '110005_01',
      name: 'Renelle',
      element: 'Flame',
      weapon: 'Dagger',
      rarity: 3,
    },
    {
      id: '100042_02',
      name: 'Gala Gatov',
      element: 'Flame',
      weapon: 'Axe',
      limited: true,
    },
    {
      id: '100003_10',
      name: 'Child Ranzal',
      element: 'Flame',
      weapon: 'Axe',
      aliases: 'cranzal, crapzal',
    },
    {
      id: '100010_07',
      name: 'Halloween Mym',
      element: 'Flame',
      weapon: 'Axe',
      uniqueDragon: true,
      limited: true,
      aliases: 'hmym',
    },
    {
      id: '110263_01',
      name: 'Ramona',
      element: 'Flame',
      weapon: 'Axe',
    },
    {
      id: '110056_01',
      name: 'Yue',
      element: 'Flame',
      weapon: 'Axe',
      rarity: 4,
    },
    {
      id: '110007_01',
      name: 'Vanessa',
      element: 'Flame',
      weapon: 'Axe',
      rarity: 4,
    },
    {
      id: '110378_01',
      name: 'Panther',
      element: 'Flame',
      weapon: 'Lance',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '100002_15',
      name: 'Kimono Elisanne',
      element: 'Flame',
      weapon: 'Lance',
      aliases: 'kelly',
    },
    {
      id: '110357_01',
      name: 'Nadine',
      element: 'Flame',
      weapon: 'Lance',
    },
    {
      id: '100010_04',
      name: 'Gala Mym',
      element: 'Flame',
      weapon: 'Lance',
      uniqueDragon: true,
      limited: true,
      aliases: 'gmym',
    },
    {
      id: '110260_01',
      name: 'Emma',
      element: 'Flame',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '110299_01',
      name: 'Xuan Zang',
      element: 'Flame',
      weapon: 'Lance',
      rarity: 4,
      limited: true,
    },
    {
      id: '110001_01',
      name: 'Alain',
      element: 'Flame',
      weapon: 'Lance',
      rarity: 3,
    },
    {
      id: '100005_08',
      name: 'Summer Alex',
      element: 'Flame',
      weapon: 'Bow',
      aliases: 'salex',
    },
    {
      id: '110342_01',
      name: 'Chelsea',
      element: 'Flame',
      weapon: 'Bow',
    },
    {
      id: '100029_02',
      name: 'Gala Sarisse',
      element: 'Flame',
      weapon: 'Bow',
      limited: true,
    },
    {
      id: '110011_02',
      name: 'Valentine\'s Ezelith',
      element: 'Flame',
      weapon: 'Bow',
      rarity: 4,
      aliases: 'vezelith',
    },
    {
      id: '110003_01',
      name: 'Joe',
      element: 'Flame',
      weapon: 'Bow',
      rarity: 3,
    },
    {
      id: '100004_19',
      name: 'Yukata Cleo',
      element: 'Flame',
      weapon: 'Wand',
      aliases: 'ycleo',
    },
    {
      id: '110375_01',
      name: 'Seimei',
      element: 'Flame',
      weapon: 'Wand',
      limited: true,
    },
    {
      id: '110053_03',
      name: 'Incognito Nefaria',
      element: 'Flame',
      weapon: 'Wand',
      aliases: 'inefaria',
    },
    {
      id: '110354_01',
      name: 'Mega Man',
      element: 'Flame',
      weapon: 'Wand',
      uniqueDragon: true,
    },
    {
      id: '110032_02',
      name: 'Student Maribelle',
      element: 'Flame',
      weapon: 'Wand',
      aliases: 'smaribelle',
    },
    {
      id: '110009_01',
      name: 'Sinoa',
      element: 'Flame',
      weapon: 'Wand',
      rarity: 4,
    },
    {
      id: '110004_01',
      name: 'Xania',
      element: 'Flame',
      weapon: 'Wand',
      rarity: 3,
    },
    {
      id: '110399_01',
      name: 'Ayaha & Otoha',
      element: 'Flame',
      weapon: 'Staff',
      uniqueDragon: true,
      aliases: 'twins, ayaoto',
    },
    {
      id: '110374_01',
      name: 'Kuzunoha',
      element: 'Flame',
      weapon: 'Staff',
      limited: true,
    },
    {
      id: '110337_03',
      name: 'Yukata Cassandra',
      element: 'Flame',
      weapon: 'Staff',
      aliases: 'ycass',
    },
    {
      id: '110043_02',
      name: 'Valentine\'s Hildegarde',
      element: 'Flame',
      weapon: 'Staff',
      aliases: 'vhildegarde',
    },
    {
      id: '110257_02',
      name: 'Halloween Lowen',
      element: 'Flame',
      weapon: 'Staff',
      rarity: 4,
      limited: true,
      aliases: 'howen, hlowen',
    },
    {
      id: '110269_01',
      name: 'Verica',
      element: 'Flame',
      weapon: 'Staff',
      rarity: 4,
    },
    {
      id: '110006_01',
      name: 'Aurien',
      element: 'Flame',
      weapon: 'Staff',
      rarity: 3,
    },
    {
      id: '110367_03',
      name: 'Dragonyule Ilia',
      element: 'Flame',
      weapon: 'Manacaster',
      limited: true,
      aliases: 'dyilia',
    },
    {
      id: '110382_01',
      name: 'Faris',
      element: 'Flame',
      weapon: 'Manacaster',
    },
    {
      id: '100013_04',
      name: 'Gala Leonidas',
      element: 'Flame',
      weapon: 'Manacaster',
      uniqueDragon: true,
      limited: true,
      aliases: 'gleonidas',
    },
    {
      id: '110313_03',
      name: 'Summer Ieyasu',
      element: 'Water',
      weapon: 'Sword',
      limited: true,
      aliases: 'syasu',
    },
    {
      id: '110363_01',
      name: 'Eugene',
      element: 'Water',
      weapon: 'Sword',
    },
    {
      id: '110255_02',
      name: 'Summer Celliera',
      element: 'Water',
      weapon: 'Sword',
      aliases: 'scelly',
    },
    {
      id: '110022_01',
      name: 'Xander',
      element: 'Water',
      weapon: 'Sword',
    },
    {
      id: '110301_02',
      name: 'Halloween Odetta',
      element: 'Water',
      weapon: 'Sword',
      rarity: 4,
      limited: true,
      aliases: 'hodetta',
    },
    {
      id: '110015_01',
      name: 'Zardin',
      element: 'Water',
      weapon: 'Sword',
      rarity: 3,
    },
    {
      id: '110395_01',
      name: 'Regina',
      element: 'Water',
      weapon: 'Blade',
    },
    {
      id: '100045_01',
      name: 'Gala Mascula',
      element: 'Water',
      weapon: 'Blade',
      limited: true,
      aliases: 'gmascula',
    },
    {
      id: '110341_03',
      name: 'Halloween Akasha',
      element: 'Water',
      weapon: 'Blade',
      limited: true,
      aliases: 'hakasha, spooky bacon tits',
    },
    {
      id: '110295_01',
      name: 'Valerio',
      element: 'Water',
      weapon: 'Blade',
    },
    {
      id: '100003_02',
      name: 'Summer Ranzal',
      element: 'Water',
      weapon: 'Blade',
      rarity: 4,
      aliases: 'sranzal',
    },
    {
      id: '110252_01',
      name: 'Celliera',
      element: 'Water',
      weapon: 'Blade',
      rarity: 4,
      limited: true,
      aliases: 'celery',
    },
    {
      id: '110016_01',
      name: 'Jurota',
      element: 'Water',
      weapon: 'Blade',
      rarity: 3,
    },
    {
      id: '110385_01',
      name: 'Humanoid Mercury',
      element: 'Water',
      weapon: 'Dagger',
      uniqueDragon: true,
      aliases: 'hmercury',
    },
    {
      id: '110360_01',
      name: 'Tiki',
      element: 'Water',
      weapon: 'Dagger',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '110296_01',
      name: 'Mitsuba',
      element: 'Water',
      weapon: 'Dagger',
    },
    {
      id: '100004_02',
      name: 'Dragonyule Cleo',
      element: 'Water',
      weapon: 'Dagger',
      limited: true,
      aliases: 'dycleo',
    },
    {
      id: '110265_01',
      name: 'Renee',
      element: 'Water',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110253_01',
      name: 'Orsem',
      element: 'Water',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110020_01',
      name: 'Luther',
      element: 'Water',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110383_01',
      name: 'Finni',
      element: 'Water',
      weapon: 'Axe',
    },
    {
      id: '110355_01',
      name: 'Lazry',
      element: 'Water',
      weapon: 'Axe',
    },
    {
      id: '100002_13',
      name: 'Gala Elisanne',
      element: 'Water',
      weapon: 'Axe',
      limited: true,
      aliases: 'gelly',
    },
    {
      id: '110042_02',
      name: 'Summer Julietta',
      element: 'Water',
      weapon: 'Axe',
      aliases: 'sjuli',
    },
    {
      id: '110018_01',
      name: 'Karina',
      element: 'Water',
      weapon: 'Axe',
      rarity: 4,
    },
    {
      id: '110258_01',
      name: 'Pietro',
      element: 'Water',
      weapon: 'Axe',
      rarity: 3,
    },
    {
      id: '110012_01',
      name: 'Rex',
      element: 'Water',
      weapon: 'Axe',
      rarity: 3,
    },
    {
      id: '110352_03',
      name: 'Faeblessed Tobias',
      element: 'Water',
      weapon: 'Lance',
      aliases: 'faebias',
    },
    {
      id: '110364_01',
      name: 'Catherine',
      element: 'Water',
      weapon: 'Lance',
    },
    {
      id: '110328_01',
      name: 'Fjorm',
      element: 'Water',
      weapon: 'Lance',
      limited: true,
    },
    {
      id: '110021_01',
      name: 'Xainfried',
      element: 'Water',
      weapon: 'Lance',
    },
    {
      id: '110356_01',
      name: 'Gauld',
      element: 'Water',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '100002_01',
      name: 'Elisanne',
      element: 'Water',
      weapon: 'Lance',
      rarity: 4,
      aliases: 'elly',
    },
    {
      id: '110058_01',
      name: 'Jakob',
      element: 'Water',
      weapon: 'Lance',
      rarity: 3,
    },
    {
      id: '110014_01',
      name: 'Cibella',
      element: 'Water',
      weapon: 'Lance',
      rarity: 3,
    },
    {
      id: '110366_01',
      name: 'Pinon',
      element: 'Water',
      weapon: 'Bow',
    },
    {
      id: '100029_03',
      name: 'Hunter Sarisse',
      element: 'Water',
      weapon: 'Bow',
      limited: true,
      aliases: 'hsarisse',
    },
    {
      id: '110317_01',
      name: 'Laranoa',
      element: 'Water',
      weapon: 'Bow',
    },
    {
      id: '110053_02',
      name: 'Dragonyule Nefaria',
      element: 'Water',
      weapon: 'Bow',
      rarity: 4,
      limited: true,
      aliases: 'dynefaria',
    },
    {
      id: '110013_01',
      name: 'Waike',
      element: 'Water',
      weapon: 'Bow',
      rarity: 3,
    },
    {
      id: '100004_17',
      name: 'Forager Cleo',
      element: 'Water',
      weapon: 'Wand',
      aliases: 'fleo, fcleo',
    },
    {
      id: '110362_01',
      name: 'Yurius',
      element: 'Water',
      weapon: 'Wand',
      dragonDrive: true,
    },
    {
      id: '110252_01',
      name: 'Lily',
      element: 'Water',
      weapon: 'Wand',
    },
    {
      id: '100017_03',
      name: 'Gala Emile',
      element: 'Water',
      weapon: 'Wand',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '110300_01',
      name: 'Pipple',
      element: 'Water',
      weapon: 'Wand',
      rarity: 4,
    },
    {
      id: '110063_02',
      name: 'Summer Estelle',
      element: 'Water',
      weapon: 'Wand',
      rarity: 4,
      aliases: 'sestelle',
    },
    {
      id: '110022_02',
      name: 'Dragonyule Xander',
      element: 'Water',
      weapon: 'Wand',
      rarity: 4,
      limited: true,
      aliases: 'dyxander',
    },
    {
      id: '110396_01',
      name: 'Sandalphon',
      element: 'Water',
      weapon: 'Staff',
      dragonDrive: true,
    },
    {
      id: '110252_02',
      name: 'Dragonyule Lily',
      element: 'Water',
      weapon: 'Staff',
      limited: true,
      aliases: 'dylily',
    },
    {
      id: '110351_01',
      name: 'Jiang Ziya',
      element: 'Water',
      weapon: 'Staff',
      aliases: 'jz',
    },
    {
      id: '110029_02',
      name: 'Nurse Aeleen',
      element: 'Water',
      weapon: 'Staff',
      rarity: 4,
      aliases: 'naeleen',
    },
    {
      id: '110019_01',
      name: 'Thaniel',
      element: 'Water',
      weapon: 'Staff',
      rarity: 4,
    },
    {
      id: '110017_01',
      name: 'Ricardt',
      element: 'Water',
      weapon: 'Staff',
      rarity: 3,
    },
    {
      id: '100029_04',
      name: 'Sharpshooter Sarisse',
      element: 'Water',
      weapon: 'Manacaster',
      aliases: 'fortnite',
    },
    {
      id: '110376_01',
      name: 'Yoshitsune',
      element: 'Water',
      weapon: 'Manacaster',
      limited: true,
    },
    {
      id: '110370_01',
      name: 'Lapis',
      element: 'Water',
      weapon: 'Manacaster',
    },
    {
      id: '110392_01',
      name: 'Nino',
      element: 'Wind',
      weapon: 'Sword',
      dragonDrive: true,
    },
    {
      id: '110379_01',
      name: 'Mona',
      element: 'Wind',
      weapon: 'Sword',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '100018_02',
      name: 'Gala Leif',
      element: 'Wind',
      weapon: 'Sword',
      limited: true,
      aliases: 'gleif',
    },
    {
      id: '100002_06',
      name: 'Wedding Elisanne',
      element: 'Wind',
      weapon: 'Sword',
      aliases: 'welly',
    },
    {
      id: '100003_07',
      name: 'Gala Ranzal',
      element: 'Wind',
      weapon: 'Sword',
      limited: true,
      aliases: 'granzal',
    },
    {
      id: '110038_02',
      name: 'Templar Hope',
      element: 'Wind',
      weapon: 'Sword',
      rarity: 4,
      aliases: 'thope',
    },
    {
      id: '110315_01',
      name: 'Ku Hai',
      element: 'Wind',
      weapon: 'Sword',
      rarity: 4,
    },
    {
      id: '100019_02',
      name: 'Harle',
      element: 'Wind',
      weapon: 'Blade',
    },
    {
      id: '110349_04',
      name: 'Yukata Lathna',
      element: 'Wind',
      weapon: 'Blade',
      aliases: 'ylathna',
    },
    {
      id: '110296_02',
      name: 'Forager Mitsuba',
      element: 'Wind',
      weapon: 'Blade',
      aliases: 'fmitsuba',
    },
    {
      id: '110352_01',
      name: 'Tobias',
      element: 'Wind',
      weapon: 'Blade',
    },
    {
      id: '110307_01',
      name: 'Victor',
      element: 'Wind',
      weapon: 'Blade',
    },
    {
      id: '110310_01',
      name: 'Addis',
      element: 'Wind',
      weapon: 'Blade',
      rarity: 4,
      limited: true,
    },
    {
      id: '110030_01',
      name: 'Musashi',
      element: 'Wind',
      weapon: 'Blade',
      rarity: 4,
    },
    {
      id: '110027_01',
      name: 'Melody',
      element: 'Wind',
      weapon: 'Blade',
      rarity: 3,
    },
    {
      id: '110365_03',
      name: 'Dragonyule Nevin',
      element: 'Wind',
      weapon: 'Dagger',
      limited: true,
      aliases: 'dynevin',
    },
    {
      id: '100007_07',
      name: 'Gala Notte',
      element: 'Wind',
      weapon: 'Dagger',
      dragonDrive: true,
      limited: true,
      aliases: 'gnotte',
    },
    {
      id: '110066_02',
      name: 'Summer Norwin',
      element: 'Wind',
      weapon: 'Dagger',
      aliases: 'snorwin',
    },
    {
      id: '110002_02',
      name: 'Wedding Aoi',
      element: 'Wind',
      weapon: 'Dagger',
      aliases: 'waoi',
    },
    {
      id: '110314_01',
      name: 'Su Fang',
      element: 'Wind',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110026_01',
      name: 'Francesca',
      element: 'Wind',
      weapon: 'Dagger',
      rarity: 3,
    },
    {
      id: '110401_01',
      name: 'Shingen',
      element: 'Wind',
      weapon: 'Axe',
      limited: true,
    },
    {
      id: '100006_11',
      name: 'Kimono Luca',
      element: 'Wind',
      weapon: 'Axe',
      aliases: 'kluca',
    },
    {
      id: '110041_02',
      name: 'Summer Amane',
      element: 'Wind',
      weapon: 'Axe',
      limited: true,
    },
    {
      id: '110027_02',
      name: 'Valentine\'s Melody',
      element: 'Wind',
      weapon: 'Axe',
      limited: true,
      aliases: 'velody',
    },
    {
      id: '110268_01',
      name: 'Lin You',
      element: 'Wind',
      weapon: 'Axe',
    },
    {
      id: '100003_01',
      name: 'Ranzal',
      element: 'Wind',
      weapon: 'Axe',
      rarity: 4,
    },
    {
      id: '110023_01',
      name: 'Johanna',
      element: 'Wind',
      weapon: 'Axe',
      rarity: 3,
    },
    {
      id: '110403_01',
      name: 'Izumo',
      element: 'Wind',
      weapon: 'Lance',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '110285_01',
      name: 'Grimnir',
      element: 'Wind',
      weapon: 'Lance',
    },
    {
      id: '110270_02',
      name: 'Halloween Melsa',
      element: 'Wind',
      weapon: 'Lance',
      limited: true,
      aliases: 'hmelsa',
    },
    {
      id: '110353_01',
      name: 'Kirsty',
      element: 'Wind',
      weapon: 'Lance',
    },
    {
      id: '110318_01',
      name: 'Sylas',
      element: 'Wind',
      weapon: 'Lance',
    },
    {
      id: '100014_03',
      name: 'Phares',
      element: 'Wind',
      weapon: 'Lance',
      dragonDrive: true,
    },
    {
      id: '110302_01',
      name: 'Pia',
      element: 'Wind',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '110029_01',
      name: 'Aeleen',
      element: 'Wind',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '110387_01',
      name: 'Humanoid Midgardsormr',
      element: 'Wind',
      weapon: 'Bow',
      uniqueDragon: true,
      limited: true,
      aliases: 'hmiddy, hmids',
    },
    {
      id: '110342_03',
      name: 'Valentine\'s Chelsea',
      element: 'Wind',
      weapon: 'Bow',
      limited: true,
      aliases: 'vchelsea',
    },
    {
      id: '110368_01',
      name: 'Meene',
      element: 'Wind',
      weapon: 'Bow',
    },
    {
      id: '110267_01',
      name: 'Hawk',
      element: 'Wind',
      weapon: 'Bow',
    },
    {
      id: '110256_01',
      name: 'Louise',
      element: 'Wind',
      weapon: 'Bow',
    },
    {
      id: '110350_01',
      name: 'Joachim',
      element: 'Wind',
      weapon: 'Bow',
      rarity: 4,
    },
    {
      id: '110031_01',
      name: 'Eleonora',
      element: 'Wind',
      weapon: 'Bow',
      rarity: 4,
    },
    {
      id: '110028_01',
      name: 'Philia',
      element: 'Wind',
      weapon: 'Bow',
      rarity: 3,
    },
    {
      id: '110397_01',
      name: 'Basileus',
      element: 'Wind',
      weapon: 'Wand',
    },
    {
      id: '110386_01',
      name: 'Myriam',
      element: 'Wind',
      weapon: 'Wand',
    },
    {
      id: '110009_02',
      name: 'Summer Sinoa',
      element: 'Wind',
      weapon: 'Wand',
      aliases: 'ssinoa',
    },
    {
      id: '110032_01',
      name: 'Maribelle',
      element: 'Wind',
      weapon: 'Wand',
    },
    {
      id: '110021_03',
      name: 'Dragonyule Xainfried',
      element: 'Wind',
      weapon: 'Wand',
      limited: true,
      aliases: 'dyxainfried',
    },
    {
      id: '110340_01',
      name: 'Noelle',
      element: 'Wind',
      weapon: 'Wand',
      rarity: 4,
    },
    {
      id: '110025_01',
      name: 'Nicolas',
      element: 'Wind',
      weapon: 'Wand',
      rarity: 3,
    },
    {
      id: '110340_02',
      name: 'Formal Noelle',
      element: 'Wind',
      weapon: 'Staff',
      aliases: 'fnoelle',
    },
    {
      id: '110341_01',
      name: 'Akasha',
      element: 'Wind',
      weapon: 'Staff',
      aliases: 'bacon tits',
    },
    {
      id: '110004_02',
      name: 'Wedding Xania',
      element: 'Wind',
      weapon: 'Staff',
      rarity: 4,
      aliases: 'wania',
    },
    {
      id: '110257_01',
      name: 'Lowen',
      element: 'Wind',
      weapon: 'Staff',
      rarity: 4,
    },
    {
      id: '110024_01',
      name: 'Sophie',
      element: 'Wind',
      weapon: 'Staff',
      rarity: 3,
    },
    {
      id: '110394_01',
      name: 'Cecile',
      element: 'Wind',
      weapon: 'Manacaster',
    },
    {
      id: '110389_01',
      name: 'Saiga',
      element: 'Wind',
      weapon: 'Manacaster',
    },
    {
      id: '110350_02',
      name: 'Formal Joachim',
      element: 'Wind',
      weapon: 'Manacaster',
      aliases: 'fjoachim',
    },
    {
      id: '100018_07',
      name: 'Civilian Leif',
      element: 'Light',
      weapon: 'Sword',
      aliases: 'cleif',
    },
    {
      id: '110371_01',
      name: 'Pecorine',
      element: 'Light',
      weapon: 'Sword',
    },
    {
      id: '100001_08',
      name: 'Gala Prince',
      element: 'Light',
      weapon: 'Sword',
      limited: true,
      aliases: 'goof, gala euden',
    },
    {
      id: '110327_01',
      name: 'Alfonse',
      element: 'Light',
      weapon: 'Sword',
    },
    {
      id: '110274_01',
      name: 'Albert',
      element: 'Light',
      weapon: 'Sword',
    },
    {
      id: '110301_01',
      name: 'Odetta',
      element: 'Light',
      weapon: 'Sword',
      rarity: 4,
    },
    {
      id: '110035_01',
      name: 'Raemond',
      element: 'Light',
      weapon: 'Sword',
      rarity: 3,
    },
    {
      id: '110398_01',
      name: 'Humanoid Jupiter',
      element: 'Light',
      weapon: 'Blade',
      uniqueDragon: true,
      aliases: 'hjupiter',
    },
    {
      id: '110369_01',
      name: 'Mordecai',
      element: 'Light',
      weapon: 'Blade',
      aliases: 'morty',
    },
    {
      id: '100006_09',
      name: 'Gala Luca',
      element: 'Light',
      weapon: 'Blade',
      limited: true,
      aliases: 'gluca',
    },
    {
      id: '110015_02',
      name: 'Beautician Zardin',
      element: 'Light',
      weapon: 'Blade',
      aliases: 'bardin',
    },
    {
      id: '110348_01',
      name: 'Hanabusa',
      element: 'Light',
      weapon: 'Blade',
      rarity: 4,
      limited: true,
      aliases: 'hanabussy',
    },
    {
      id: '110064_01',
      name: 'Yachiyo',
      element: 'Light',
      weapon: 'Blade',
      rarity: 4,
    },
    {
      id: '110049_02',
      name: 'Halloween Edward',
      element: 'Light',
      weapon: 'Blade',
      rarity: 3,
      limited: true,
      aliases: 'hedward',
    },
    {
      id: '110393_01',
      name: 'Farren',
      element: 'Light',
      weapon: 'Dagger',
      dragonDrive: true,
    },
    {
      id: '110281_02',
      name: 'Yukata Curran',
      element: 'Light',
      weapon: 'Dagger',
      aliases: 'ycurran, ycurry',
    },
    {
      id: '110324_01',
      name: 'Wu Kong',
      element: 'Light',
      weapon: 'Dagger',
      limited: true,
    },
    {
      id: '110345_01',
      name: 'Mitsuhide',
      element: 'Light',
      weapon: 'Dagger',
      limited: true,
    },
    {
      id: '110319_01',
      name: 'Fleur',
      element: 'Light',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110276_01',
      name: 'Fritz',
      element: 'Light',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110037_01',
      name: 'Irfan',
      element: 'Light',
      weapon: 'Dagger',
      rarity: 3,
    },
    {
      id: '110334_02',
      name: 'Gala Audric',
      element: 'Light',
      weapon: 'Axe',
      limited: true,
      aliases: 'gaudric',
    },
    {
      id: '110380_01',
      name: 'Sophie (Persona)',
      element: 'Light',
      weapon: 'Axe',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '110322_01',
      name: 'Zhu Bajie',
      element: 'Light',
      weapon: 'Axe',
    },
    {
      id: '110036_03',
      name: 'Dragonyule Malora',
      element: 'Light',
      weapon: 'Axe',
      limited: true,
      aliases: 'dymalora',
    },
    {
      id: '110042_01',
      name: 'Julietta',
      element: 'Light',
      weapon: 'Axe',
    },
    {
      id: '100016_03',
      name: 'Valyx',
      element: 'Light',
      weapon: 'Axe',
      uniqueDragon: true,
    },
    {
      id: '100006_03',
      name: 'Summer Luca',
      element: 'Light',
      weapon: 'Axe',
      rarity: 4,
      aliases: 'sluca',
    },
    {
      id: '110033_01',
      name: 'Linus',
      element: 'Light',
      weapon: 'Axe',
      rarity: 3,
    },
    {
      id: '110381_01',
      name: 'Ryszarda',
      element: 'Light',
      weapon: 'Lance',
    },
    {
      id: '110358_01',
      name: 'Sharena',
      element: 'Light',
      weapon: 'Lance',
    },
    {
      id: '110007_02',
      name: 'Hunter Vanessa',
      element: 'Light',
      weapon: 'Lance',
      limited: true,
      aliases: 'hnessa, hvanesaa',
    },
    {
      id: '100002_02',
      name: 'Halloween Elisanne',
      element: 'Light',
      weapon: 'Lance',
      limited: true,
      aliases: 'helly, helisanne',
    },
    {
      id: '110275_01',
      name: 'Annelie',
      element: 'Light',
      weapon: 'Lance',
    },
    {
      id: '110323_01',
      name: 'Sha Wujing',
      element: 'Light',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '110039_01',
      name: 'Ryozen',
      element: 'Light',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '110034_01',
      name: 'Malka',
      element: 'Light',
      weapon: 'Lance',
      rarity: 3,
    },
    {
      id: '110391_01',
      name: 'Isaac',
      element: 'Light',
      weapon: 'Bow',
    },
    {
      id: '110010_02',
      name: 'Summer Mikoto',
      element: 'Light',
      weapon: 'Bow',
      aliases: 'skoto',
    },
    {
      id: '100004_04',
      name: 'Summer Cleo',
      element: 'Light',
      weapon: 'Bow',
      aliases: 'sleo',
    },
    {
      id: '110303_01',
      name: 'Elias',
      element: 'Light',
      weapon: 'Bow',
      rarity: 4,
      limited: true,
    },
    {
      id: '110040_01',
      name: 'Rawn',
      element: 'Light',
      weapon: 'Bow',
      rarity: 4,
    },
    {
      id: '100006_01',
      name: 'Luca',
      element: 'Light',
      weapon: 'Bow',
      rarity: 4,
    },
    {
      id: '110036_01',
      name: 'Malora',
      element: 'Light',
      weapon: 'Bow',
      rarity: 3,
    },
    {
      id: '100015_08',
      name: 'Summer Chelle',
      element: 'Light',
      weapon: 'Wand',
      uniqueDragon: true,
      aliases: 'schelle',
    },
    {
      id: '110299_02',
      name: 'Radiant Xuan Zang',
      element: 'Light',
      weapon: 'Wand',
      aliases: 'rxz',
    },
    {
      id: '110361_01',
      name: 'Peony',
      element: 'Light',
      weapon: 'Wand',
      limited: true,
    },
    {
      id: '110305_01',
      name: 'Lucretia',
      element: 'Light',
      weapon: 'Wand',
    },
    {
      id: '110347_01',
      name: 'Chitose',
      element: 'Light',
      weapon: 'Wand',
      rarity: 4,
      limited: true,
      aliases: 'cheetos',
    },
    {
      id: '110041_01',
      name: 'Amane',
      element: 'Light',
      weapon: 'Wand',
      rarity: 4,
    },
    {
      id: '110316_01',
      name: 'Xiao Lei',
      element: 'Light',
      weapon: 'Wand',
      rarity: 3,
    },
    {
      id: '100009_08',
      name: 'Gala Zena',
      element: 'Light',
      weapon: 'Staff',
      limited: true,
      aliases: 'gzena',
    },
    {
      id: '110043_01',
      name: 'Hildegarde',
      element: 'Light',
      weapon: 'Staff',
    },
    {
      id: '100007_10',
      name: 'Kimono Notte',
      element: 'Light',
      weapon: 'Staff',
      dragonDrive: true,
      aliases: 'knotte, kimonotte',
    },
    {
      id: '110277_01',
      name: 'Felicia',
      element: 'Light',
      weapon: 'Staff',
      rarity: 4,
      limited: true,
    },
    {
      id: '110304_01',
      name: 'Vixel',
      element: 'Light',
      weapon: 'Staff',
      rarity: 4,
    },
    {
      id: '110047_02',
      name: 'Halloween Althemia',
      element: 'Light',
      weapon: 'Staff',
      rarity: 4,
      limited: true,
      aliases: 'halthemia',
    },
    {
      id: '110063_01',
      name: 'Estelle',
      element: 'Light',
      weapon: 'Staff',
      rarity: 3,
    },
    {
      id: '110038_01',
      name: 'Hope',
      element: 'Light',
      weapon: 'Staff',
      rarity: 3,
    },
    {
      id: '100032_07',
      name: 'Halloween Laxi',
      element: 'Light',
      weapon: 'Manacaster',
      limited: true,
      aliases: 'hlaxi',
    },
    {
      id: '110384_01',
      name: 'Eirene',
      element: 'Light',
      weapon: 'Manacaster',
    },
    {
      id: '110367_01',
      name: 'Ilia',
      element: 'Light',
      weapon: 'Manacaster',
    },
    {
      id: '110003_02',
      name: 'Sharpshooter Joe',
      element: 'Light',
      weapon: 'Manacaster',
      rarity: 3,
    },
    {
      id: '100031_03',
      name: 'Alberius',
      element: 'Shadow',
      weapon: 'Sword',
    },
    {
      id: '100005_02',
      name: 'Gala Alex',
      element: 'Shadow',
      weapon: 'Sword',
      limited: true,
      aliases: 'galex',
    },
    {
      id: '110325_01',
      name: 'Yaten',
      element: 'Shadow',
      weapon: 'Sword',
    },
    {
      id: '110334_01',
      name: 'Audric',
      element: 'Shadow',
      weapon: 'Sword',
      rarity: 4,
    },
    {
      id: '110050_01',
      name: 'Berserker',
      element: 'Shadow',
      weapon: 'Sword',
      rarity: 4,
      aliases: 'zerker',
    },
    {
      id: '110046_01',
      name: 'Rodrigo',
      element: 'Shadow',
      weapon: 'Sword',
      rarity: 3,
    },
    {
      id: '100054_01',
      name: 'Gala Zethia',
      element: 'Shadow',
      weapon: 'Blade',
      dragonDrive: true,
      limited: true,
      aliases: 'gethia',
    },
    {
      id: '110271_01',
      name: 'Linnea',
      element: 'Shadow',
      weapon: 'Blade',
    },
    {
      id: '110326_01',
      name: 'Natalie',
      element: 'Shadow',
      weapon: 'Blade',
    },
    {
      id: '110313_01',
      name: 'Ieyasu',
      element: 'Shadow',
      weapon: 'Blade',
      limited: true,
    },
    {
      id: '110262_01',
      name: 'Aldred',
      element: 'Shadow',
      weapon: 'Blade',
      rarity: 4,
      dragonDrive: true,
      limited: true,
    },
    {
      id: '110343_01',
      name: 'Durant',
      element: 'Shadow',
      weapon: 'Blade',
      rarity: 4,
    },
    {
      id: '110044_01',
      name: 'Taro',
      element: 'Shadow',
      weapon: 'Blade',
      rarity: 3,
    },
    {
      id: '100001_12',
      name: 'Summer Prince',
      element: 'Shadow',
      weapon: 'Dagger',
      limited: true,
      aliases: 'summer euden, soof',
    },
    {
      id: '110377_01',
      name: 'Joker',
      element: 'Shadow',
      weapon: 'Dagger',
      dragonDrive: true,
      limited: true,
    },
    {
      id: '110365_01',
      name: 'Nevin',
      element: 'Shadow',
      weapon: 'Dagger',
    },
    {
      id: '110306_01',
      name: 'Bellina',
      element: 'Shadow',
      weapon: 'Dagger',
      dragonDrive: true,
    },
    {
      id: '110336_01',
      name: 'Delphi',
      element: 'Shadow',
      weapon: 'Dagger',
    },
    {
      id: '100005_01',
      name: 'Alex',
      element: 'Shadow',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110052_01',
      name: 'Orion',
      element: 'Shadow',
      weapon: 'Dagger',
      rarity: 4,
    },
    {
      id: '110067_01',
      name: 'Vida',
      element: 'Shadow',
      weapon: 'Dagger',
      rarity: 3,
    },
    {
      id: '110048_01',
      name: 'Vice',
      element: 'Shadow',
      weapon: 'Dagger',
      rarity: 3,
    },
    {
      id: '110307_02',
      name: 'Dragonyule Victor',
      element: 'Shadow',
      weapon: 'Axe',
      limited: true,
      aliases: 'dyvictor',
    },
    {
      id: '110335_02',
      name: 'Summer Patia',
      element: 'Shadow',
      weapon: 'Axe',
      aliases: 'spatia',
    },
    {
      id: '110281_01',
      name: 'Curran',
      element: 'Shadow',
      weapon: 'Axe',
      aliases: 'curry',
    },
    {
      id: '110311_01',
      name: 'Sazanka',
      element: 'Shadow',
      weapon: 'Axe',
      rarity: 4,
      limited: true,
    },
    {
      id: '110045_01',
      name: 'Erik',
      element: 'Shadow',
      weapon: 'Axe',
      rarity: 3,
    },
    {
      id: '110402_01',
      name: 'Yukimura',
      element: 'Shadow',
      weapon: 'Lance',
      limited: true,
    },
    {
      id: '100013_06',
      name: 'Summer Leonidas',
      element: 'Shadow',
      weapon: 'Lance',
      dragonDrive: true,
      aliases: 'sleonidas',
    },
    {
      id: '110349_01',
      name: 'Lathna',
      element: 'Shadow',
      weapon: 'Lance',
      uniqueDragon: true,
    },
    {
      id: '110272_01',
      name: 'Forte',
      element: 'Shadow',
      weapon: 'Lance',
    },
    {
      id: '110335_01',
      name: 'Patia',
      element: 'Shadow',
      weapon: 'Lance',
      rarity: 4,
    },
    {
      id: '110312_01',
      name: 'Botan',
      element: 'Shadow',
      weapon: 'Lance',
      rarity: 4,
      limited: true,
    },
    {
      id: '110254_01',
      name: 'Zace',
      element: 'Shadow',
      weapon: 'Lance',
      rarity: 3,
    },
    {
      id: '110318_02',
      name: 'Halloween Sylas',
      element: 'Shadow',
      weapon: 'Bow',
      limited: true,
      aliases: 'hsylas',
    },
    {
      id: '110018_02',
      name: 'Opera Karina',
      element: 'Shadow',
      weapon: 'Bow',
      aliases: 'okarina, operina',
    },
    {
      id: '100015_04',
      name: 'Chelle',
      element: 'Shadow',
      weapon: 'Bow',
      uniqueDragon: true,
    },
    {
      id: '110310_02',
      name: 'Valentine\'s Addis',
      element: 'Shadow',
      weapon: 'Bow',
      aliases: 'vaddis',
    },
    {
      id: '110053_01',
      name: 'Nefaria',
      element: 'Shadow',
      weapon: 'Bow',
    },
    {
      id: '110066_01',
      name: 'Norwin',
      element: 'Shadow',
      weapon: 'Bow',
      rarity: 4,
    },
    {
      id: '110388_01',
      name: 'Vania',
      element: 'Shadow',
      weapon: 'Wand',
    },
    {
      id: '100009_07',
      name: 'Zena',
      element: 'Shadow',
      weapon: 'Wand',
    },
    {
      id: '110337_01',
      name: 'Cassandra',
      element: 'Shadow',
      weapon: 'Wand',
    },
    {
      id: '100004_10',
      name: 'Gala Cleo',
      element: 'Shadow',
      weapon: 'Wand',
      limited: true,
      aliases: 'gleo',
    },
    {
      id: '110333_01',
      name: 'Veronica',
      element: 'Shadow',
      weapon: 'Wand',
      limited: true,
    },
    {
      id: '110051_01',
      name: 'Kleimann',
      element: 'Shadow',
      weapon: 'Wand',
      rarity: 4,
    },
    {
      id: '110047_01',
      name: 'Althemia',
      element: 'Shadow',
      weapon: 'Wand',
      rarity: 3,
    },
    {
      id: '110059_01',
      name: 'Grace',
      element: 'Shadow',
      weapon: 'Staff',
    },
    {
      id: '110269_02',
      name: 'Summer Verica',
      element: 'Shadow',
      weapon: 'Staff',
      aliases: 'sverica',
    },
    {
      id: '110280_01',
      name: 'Heinwald',
      element: 'Shadow',
      weapon: 'Staff',
    },
    {
      id: '100004_01',
      name: 'Cleo',
      element: 'Shadow',
      weapon: 'Staff',
      rarity: 4,
    },
    {
      id: '110049_01',
      name: 'Edward',
      element: 'Shadow',
      weapon: 'Staff',
      rarity: 3,
    },
    {
      id: '100010_10',
      name: 'Summer Mym',
      element: 'Shadow',
      weapon: 'Manacaster',
      dragonDrive: true,
      aliases: 'smym',
    },
    {
      id: '100015_05',
      name: 'Gala Chelle',
      element: 'Shadow',
      weapon: 'Manacaster',
      uniqueDragon: true,
      limited: true,
      aliases: 'gchelle',
    },
  ],
}